### PR TITLE
New Baseline

### PR DESCRIPTION
**Pull request by FuzzicalLogic**
__**This PR need not be deployed. There are no functional benefits to this PR. **__

While RssService changed considerably, the functionality is largely the same. This PR is mostly to provide a new base for implementing a branching strategy on my fork.

### CODE REVIEW

**Comment by FuzzicalLogic** [comment]
Generally, I prefer to know what subtype I'm dealing with before I know what it applies to. 

So id tells me what type of number it is, which is generally way more important for functionality than knowing where it goes. The "model" or "class" handles where it goes, but the subtype determines what I can do with it (if that makes sense) and what I must always keep in mind.

It also allows me to group similar or related vars without having to read every varname... for example, idGuild and urlGuild and rssGuild are might be right next to each other. But in a guild only function, I'd only have to see the first few characters. For me, it's about reading and thought efficiency.

**Comment by Kyle-Undefined** [comment]
@FuzzicalLogic personally I'm against Hungarian style, and while I understand what you're saying, would rather not have that if all possible.

**Comment by FuzzicalLogic** [comment]
@Kyle-Undefined That's fair, and I'll fix it in the next PR. I would prefer to do it with the next PR because it will coincide well with the introduction of the STYLE_GUIDE.md. I hope that is alright.

**Comment by Kyle-Undefined** [comment]
@FuzzicalLogic sounds good to me dude. I've just never been a fan of it, that's all. I'll hopefully be able to test tomorrow and merge.

**Comment by FuzzicalLogic** [comment]
That's not a problem. I can work in a variety of styles.  Unless it has a computational impact, I am very very flexible. If you see a style that I introduce without thought, definitely let me know. If you're interested as to why, please ask. And if you don't like it, please tell me.

As a note: I don't code in hungarian notation primarily... just for subtypes. There's a distinct difference between noting a base type and a subtype. Base Types which can be easily determined in declaration and whose semantics can change according to environment or language. Subtypes like id are agnostic computationally, and are consistent across coding environments.

**Comment by FuzzicalLogic** [comment]
Also, I'm going to open an Issue regarding Styles and Conventions, simply so we can lock those down in case others decide to contribute. That way we don't have to discuss it in the PRs or the discord. Also we can take time in case one of us feels strongly about an idea. Of course it will be closed as soon as the STYLE_GUIDE is complete. 

The reason is because there are many code types/patterns that I haven't seen in this example of code, so I want to have a forum for which to ask, discuss and get feedback for as they come up.

**Comment by Kyle-Undefined** [comment]
@FuzzicalLogic yeah a style guide would be perfect. Personally I like method params to be camel case. But that's just me. We can flesh everything out and clean up what we come up with for the style guide as we go.

**Review by Kyle-Undefined — APPROVED** [review]
Merging from phone, haven't had chance to test locally. Looked fine from what I've seen.

**Pull request merged**
